# Generated by Django 5.2.17 on 2026-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("closed", "Closed"),
                    ("spam", "Suspected spam"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
