# Generated by Django 5.2.17 on 2026-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_enquiry_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL for the detail page. Left blank, it is built from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One line, shown on the home page card.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A sentence or two, shown on the services listing card."
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="The full description shown on the service's own page.",
                    ),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="What's included - one item per line. Shown as a tick list.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("personal-care", "Personal care (person)"),
                            ("household", "Household (house)"),
                            ("community-access", "Community access (people)"),
                            ("shared-living", "Shared living (house + heart)"),
                            ("transport", "Transport (vehicle)"),
                            ("hands-heart", "Hands and heart"),
                            ("person-heart", "Person and heart"),
                            ("hand-heart", "Supporting hand"),
                            ("heart", "Heart"),
                            ("shield-check", "Shield"),
                            ("sprout", "Sprout"),
                            ("star", "Star"),
                            ("growth", "Growth"),
                            ("calendar-check", "Calendar"),
                            ("clock-flex", "Clock"),
                            ("check-badge", "Check badge"),
                        ],
                        default="personal-care",
                        max_length=40,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Roughly 900x700. A placeholder is used when empty.",
                        upload_to="services/",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished services are hidden from the website.",
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=True,
                        help_text="Include in the footer's 'Our Services' column.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-engine description. Falls back to the summary.",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
