# Generated by Django 5.2.17 on 2026-08-08 16:12

import django.db.models.deletion
import pages.vacancy_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_seed_services"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL for this vacancy. Left blank, it is built from the title.",
                        max_length=160,
                        unique=True,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("casual", "Casual"),
                            ("contract", "Contract"),
                            ("casual_part_time", "Casual & part-time"),
                        ],
                        default="casual",
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(default="Toowoomba, QLD", max_length=140),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One line, shown in the vacancy list.", max_length=250
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="The main body of the advert."),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="One per line. Shown as a tick list."
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="One per line. Shown as a tick list."
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. “$35 - $45 per hour”.",
                        max_length=140,
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional. After this date the advert stops accepting applications.",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished vacancies are hidden from the website.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "vacancies",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_title", models.CharField(blank=True, max_length=140)),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        storage=pages.vacancy_models.PrivateMediaStorage(),
                        upload_to=pages.vacancy_models.resume_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("shortlisted", "Shortlisted"),
                            ("interviewing", "Interviewing"),
                            ("unsuccessful", "Unsuccessful"),
                            ("hired", "Hired"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty for a speculative application.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="pages.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
