# Generated by Django 5.2.17 on 2026-08-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_seed_vacancies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=140, verbose_name="Your name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                ("phone", models.CharField(max_length=40, verbose_name="Phone number")),
                (
                    "enquirer_type",
                    models.CharField(
                        choices=[
                            ("self", "Myself"),
                            ("family", "A family member or carer"),
                            ("coordinator", "A support coordinator"),
                            ("other", "Someone else"),
                        ],
                        default="self",
                        max_length=20,
                        verbose_name="This consultation is for",
                    ),
                ),
                (
                    "participant_name",
                    models.CharField(
                        blank=True,
                        help_text="If you are enquiring on someone else's behalf.",
                        max_length=140,
                        verbose_name="Participant's name",
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("self_managed", "Approved - self managed"),
                            ("plan_managed", "Approved - plan managed"),
                            ("agency_managed", "Approved - NDIA managed"),
                            ("applying", "Applying for a plan"),
                            ("not_yet", "No plan yet"),
                            ("unsure", "Not sure"),
                        ],
                        default="unsure",
                        max_length=20,
                        verbose_name="NDIS plan status",
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True,
                        help_text="Optional - it helps us come prepared.",
                        verbose_name="What would you like to talk about?",
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("home", "At my home"),
                            ("phone", "Over the phone"),
                            ("video", "Video call"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="Where would you like to meet?",
                    ),
                ),
                ("suburb", models.CharField(blank=True, max_length=120)),
                ("postcode", models.CharField(blank=True, max_length=10)),
                ("preferred_date", models.DateField(verbose_name="Preferred date")),
                (
                    "preferred_window",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8:00 AM - 12:00 PM)"),
                            ("afternoon", "Afternoon (12:00 PM - 5:00 PM)"),
                            ("any", "Any time that suits you"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="Preferred time",
                    ),
                ),
                (
                    "alternate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Alternative date"
                    ),
                ),
                (
                    "alternate_window",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning (8:00 AM - 12:00 PM)"),
                            ("afternoon", "Afternoon (12:00 PM - 5:00 PM)"),
                            ("any", "Any time that suits you"),
                        ],
                        max_length=20,
                        verbose_name="Alternative time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "Did not attend"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time actually agreed with the participant.",
                        null=True,
                    ),
                ),
                ("staff_notes", models.TextField(blank=True)),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consultations",
                        to="pages.service",
                        verbose_name="Support you're interested in",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
