# Generated by Django 5.2.17 on 2026-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_consultation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL for this profile. Left blank, it is built from the name.",
                        max_length=160,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="For example: Support Coordinator", max_length=140
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Square works best. A placeholder is used when empty.",
                        upload_to="team/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A short introduction, shown on this person's own page.",
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, help_text="One per line. Shown as a tick list."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished people are hidden from the website.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "team member",
                "ordering": ["order", "name"],
            },
        ),
    ]
