# Generated by Django 5.2.17 on 2026-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_seed_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Rightway Support Services", max_length=140
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short line under the name, e.g. “Your Path, Our Support”.",
                        max_length=200,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Used in the site header. Wide, transparent PNG works best.",
                        upload_to="branding/",
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True,
                        help_text="White version, used on the dark footer. Falls back to the main logo.",
                        upload_to="branding/",
                        verbose_name="Logo (light version)",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Browser tab icon for the website and the dashboard. Square PNG, 180x180 or larger.",
                        upload_to="branding/",
                    ),
                ),
                (
                    "footer_description",
                    models.TextField(
                        blank=True,
                        help_text="The paragraph under the logo in the footer.",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Where enquiries and applications are sent.",
                        max_length=254,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        help_text="e.g. “Mon - Fri, 8:00 AM - 5:00 PM”.",
                        max_length=140,
                        verbose_name="Office hours",
                    ),
                ),
                (
                    "abn",
                    models.CharField(blank=True, max_length=20, verbose_name="ABN"),
                ),
                (
                    "map_address",
                    models.CharField(
                        blank=True,
                        help_text="What the map should search for. Falls back to the address above.",
                        max_length=250,
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. Paste a Google Maps embed URL to pin an exact spot instead.",
                        max_length=500,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("youtube", "YouTube"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=300)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers first."
                    ),
                ),
            ],
            options={
                "ordering": ["order", "platform"],
            },
        ),
    ]
