# Generated by Django 5.2.17 on 2026-08-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_seed_site_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Leave empty to keep the platform in the list without linking to it.",
                max_length=300,
            ),
        ),
    ]
